// Code generated by protoc-gen-go. DO NOT EDIT.
// source: svcs/v1/public.proto

package svcsv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "github.com/octofoxio/sparkle/pkg/common/v1"
	v11 "github.com/octofoxio/sparkle/pkg/entities/v1"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterWithEmailInput struct {
	Email                *v1.String `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	PlainPassword        *v1.String `protobuf:"bytes,2,opt,name=PlainPassword,proto3" json:"PlainPassword,omitempty"`
	CallbackURL          *v1.String `protobuf:"bytes,3,opt,name=CallbackURL,proto3" json:"CallbackURL,omitempty"`
	DisplayName          *v1.String `protobuf:"bytes,4,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterWithEmailInput) Reset()         { *m = RegisterWithEmailInput{} }
func (m *RegisterWithEmailInput) String() string { return proto.CompactTextString(m) }
func (*RegisterWithEmailInput) ProtoMessage()    {}
func (*RegisterWithEmailInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_287017f47acf1d8d, []int{0}
}

func (m *RegisterWithEmailInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterWithEmailInput.Unmarshal(m, b)
}
func (m *RegisterWithEmailInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterWithEmailInput.Marshal(b, m, deterministic)
}
func (m *RegisterWithEmailInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterWithEmailInput.Merge(m, src)
}
func (m *RegisterWithEmailInput) XXX_Size() int {
	return xxx_messageInfo_RegisterWithEmailInput.Size(m)
}
func (m *RegisterWithEmailInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterWithEmailInput.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterWithEmailInput proto.InternalMessageInfo

func (m *RegisterWithEmailInput) GetEmail() *v1.String {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *RegisterWithEmailInput) GetPlainPassword() *v1.String {
	if m != nil {
		return m.PlainPassword
	}
	return nil
}

func (m *RegisterWithEmailInput) GetCallbackURL() *v1.String {
	if m != nil {
		return m.CallbackURL
	}
	return nil
}

func (m *RegisterWithEmailInput) GetDisplayName() *v1.String {
	if m != nil {
		return m.DisplayName
	}
	return nil
}

type RegisterWithEmailOutput struct {
	Result               *v11.User `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterWithEmailOutput) Reset()         { *m = RegisterWithEmailOutput{} }
func (m *RegisterWithEmailOutput) String() string { return proto.CompactTextString(m) }
func (*RegisterWithEmailOutput) ProtoMessage()    {}
func (*RegisterWithEmailOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_287017f47acf1d8d, []int{1}
}

func (m *RegisterWithEmailOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterWithEmailOutput.Unmarshal(m, b)
}
func (m *RegisterWithEmailOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterWithEmailOutput.Marshal(b, m, deterministic)
}
func (m *RegisterWithEmailOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterWithEmailOutput.Merge(m, src)
}
func (m *RegisterWithEmailOutput) XXX_Size() int {
	return xxx_messageInfo_RegisterWithEmailOutput.Size(m)
}
func (m *RegisterWithEmailOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterWithEmailOutput.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterWithEmailOutput proto.InternalMessageInfo

func (m *RegisterWithEmailOutput) GetResult() *v11.User {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterWithEmailInput)(nil), "sparkle.svcs.v1.RegisterWithEmailInput")
	proto.RegisterType((*RegisterWithEmailOutput)(nil), "sparkle.svcs.v1.RegisterWithEmailOutput")
}

func init() { proto.RegisterFile("svcs/v1/public.proto", fileDescriptor_287017f47acf1d8d) }

var fileDescriptor_287017f47acf1d8d = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xb1, 0x4e, 0xeb, 0x30,
	0x14, 0x86, 0x6f, 0xd3, 0x7b, 0x7b, 0x25, 0x57, 0xa8, 0x22, 0xa0, 0x92, 0x76, 0x42, 0x5d, 0xe8,
	0x64, 0xcb, 0x65, 0xec, 0x80, 0x54, 0x60, 0x40, 0xaa, 0x20, 0x4a, 0xd4, 0x82, 0x50, 0x17, 0x27,
	0x98, 0xd4, 0xaa, 0x13, 0x47, 0xb6, 0x13, 0x60, 0x62, 0xe1, 0x49, 0x18, 0x79, 0x14, 0x9e, 0x0a,
	0x39, 0x49, 0x51, 0x69, 0x91, 0x32, 0x45, 0x39, 0xfe, 0xfe, 0xff, 0xd8, 0xff, 0x39, 0xe0, 0x50,
	0xe5, 0xa1, 0x42, 0x39, 0x46, 0x69, 0x16, 0x70, 0x16, 0xc2, 0x54, 0x0a, 0x2d, 0xec, 0x8e, 0x4a,
	0x89, 0x5c, 0x71, 0x0a, 0xcd, 0x29, 0xcc, 0x71, 0xbf, 0x17, 0x8a, 0x38, 0x16, 0x49, 0x01, 0x4a,
	0x16, 0x33, 0xcd, 0x72, 0x5a, 0xb2, 0xfd, 0x2e, 0x4d, 0x34, 0xd3, 0x8c, 0x16, 0x2e, 0x99, 0xa2,
	0xb2, 0xac, 0x0f, 0xde, 0x2c, 0xd0, 0xf5, 0x68, 0xc4, 0x94, 0xa6, 0xf2, 0x96, 0xe9, 0xe5, 0x65,
	0x4c, 0x18, 0xbf, 0x4a, 0xd2, 0x4c, 0xdb, 0x08, 0xfc, 0x2b, 0xfe, 0x9c, 0xc6, 0x71, 0x63, 0xd8,
	0x1e, 0xf5, 0xe0, 0xba, 0x5d, 0xd9, 0x05, 0xe6, 0x18, 0xfa, 0x5a, 0xb2, 0x24, 0xf2, 0x4a, 0xce,
	0x3e, 0x03, 0x7b, 0x2e, 0x27, 0x2c, 0x71, 0x89, 0x52, 0x4f, 0x42, 0x3e, 0x38, 0x56, 0x9d, 0xf0,
	0x27, 0x6f, 0x8f, 0x41, 0xfb, 0x9c, 0x70, 0x1e, 0x90, 0x70, 0x35, 0xf3, 0xa6, 0x4e, 0xb3, 0x4e,
	0xbe, 0x49, 0x1b, 0xf1, 0x05, 0x53, 0x29, 0x27, 0x2f, 0xd7, 0x24, 0xa6, 0xce, 0xdf, 0x5a, 0xf1,
	0x06, 0x3d, 0x98, 0x82, 0xa3, 0x9d, 0x14, 0x6e, 0x32, 0x6d, 0x62, 0xc0, 0xa0, 0xe5, 0x51, 0x95,
	0x71, 0xbd, 0x93, 0xc3, 0x3a, 0x52, 0x63, 0x3a, 0x53, 0x54, 0x7a, 0x15, 0x38, 0x52, 0xe0, 0xbf,
	0x5f, 0x32, 0xf6, 0x12, 0xec, 0xef, 0x18, 0xdb, 0x27, 0x70, 0x6b, 0x72, 0xf0, 0xf7, 0x11, 0xf4,
	0x87, 0xf5, 0x60, 0x79, 0xcb, 0xc1, 0x9f, 0xc9, 0x2b, 0x38, 0x08, 0x45, 0xbc, 0x2d, 0x98, 0xb4,
	0xdd, 0x62, 0x65, 0x5c, 0x33, 0x6d, 0xb7, 0x71, 0x8f, 0x22, 0xa6, 0x97, 0x59, 0x60, 0xe2, 0x40,
	0x22, 0xd4, 0xe2, 0x51, 0x3c, 0x33, 0x81, 0x2a, 0x11, 0x4a, 0x57, 0x11, 0xaa, 0x56, 0x6d, 0x6c,
	0xbe, 0x39, 0x7e, 0xb7, 0x9a, 0xbe, 0x7f, 0xf7, 0x61, 0x75, 0xaa, 0x07, 0x41, 0xdf, 0xf8, 0xce,
	0xf1, 0xe7, 0x77, 0x65, 0x61, 0x2a, 0x8b, 0x39, 0x0e, 0x5a, 0xc5, 0x46, 0x9d, 0x7e, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x77, 0x56, 0xb8, 0xf5, 0xad, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SparkleClient is the client API for Sparkle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SparkleClient interface {
	RegisterWithEmail(ctx context.Context, in *RegisterWithEmailInput, opts ...grpc.CallOption) (*RegisterWithEmailOutput, error)
}

type sparkleClient struct {
	cc *grpc.ClientConn
}

func NewSparkleClient(cc *grpc.ClientConn) SparkleClient {
	return &sparkleClient{cc}
}

func (c *sparkleClient) RegisterWithEmail(ctx context.Context, in *RegisterWithEmailInput, opts ...grpc.CallOption) (*RegisterWithEmailOutput, error) {
	out := new(RegisterWithEmailOutput)
	err := c.cc.Invoke(ctx, "/sparkle.svcs.v1.Sparkle/RegisterWithEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SparkleServer is the server API for Sparkle service.
type SparkleServer interface {
	RegisterWithEmail(context.Context, *RegisterWithEmailInput) (*RegisterWithEmailOutput, error)
}

func RegisterSparkleServer(s *grpc.Server, srv SparkleServer) {
	s.RegisterService(&_Sparkle_serviceDesc, srv)
}

func _Sparkle_RegisterWithEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWithEmailInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkleServer).RegisterWithEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sparkle.svcs.v1.Sparkle/RegisterWithEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkleServer).RegisterWithEmail(ctx, req.(*RegisterWithEmailInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sparkle_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sparkle.svcs.v1.Sparkle",
	HandlerType: (*SparkleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWithEmail",
			Handler:    _Sparkle_RegisterWithEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svcs/v1/public.proto",
}
