// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/v1/primitive.proto

package commonv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gender int32

const (
	Gender_Male    Gender = 0
	Gender_Female  Gender = 1
	Gender_Unknown Gender = 2
)

var Gender_name = map[int32]string{
	0: "Male",
	1: "Female",
	2: "Unknown",
}

var Gender_value = map[string]int32{
	"Male":    0,
	"Female":  1,
	"Unknown": 2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bf86590bfc22541a, []int{0}
}

type String struct {
	Data                 string   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	IsNull               bool     `protobuf:"varint,2,opt,name=IsNull,proto3" json:"IsNull,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf86590bfc22541a, []int{0}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *String) GetIsNull() bool {
	if m != nil {
		return m.IsNull
	}
	return false
}

type Number struct {
	Data                 int64    `protobuf:"varint,1,opt,name=Data,proto3" json:"Data,omitempty"`
	IsNull               bool     `protobuf:"varint,2,opt,name=IsNull,proto3" json:"IsNull,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Number) Reset()         { *m = Number{} }
func (m *Number) String() string { return proto.CompactTextString(m) }
func (*Number) ProtoMessage()    {}
func (*Number) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf86590bfc22541a, []int{1}
}

func (m *Number) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Number.Unmarshal(m, b)
}
func (m *Number) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Number.Marshal(b, m, deterministic)
}
func (m *Number) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Number.Merge(m, src)
}
func (m *Number) XXX_Size() int {
	return xxx_messageInfo_Number.Size(m)
}
func (m *Number) XXX_DiscardUnknown() {
	xxx_messageInfo_Number.DiscardUnknown(m)
}

var xxx_messageInfo_Number proto.InternalMessageInfo

func (m *Number) GetData() int64 {
	if m != nil {
		return m.Data
	}
	return 0
}

func (m *Number) GetIsNull() bool {
	if m != nil {
		return m.IsNull
	}
	return false
}

type Timestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=Seconds,proto3" json:"Seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf86590bfc22541a, []int{2}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func init() {
	proto.RegisterEnum("sparkle.common.v1.Gender", Gender_name, Gender_value)
	proto.RegisterType((*String)(nil), "sparkle.common.v1.String")
	proto.RegisterType((*Number)(nil), "sparkle.common.v1.Number")
	proto.RegisterType((*Timestamp)(nil), "sparkle.common.v1.Timestamp")
}

func init() { proto.RegisterFile("common/v1/primitive.proto", fileDescriptor_bf86590bfc22541a) }

var fileDescriptor_bf86590bfc22541a = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2f, 0x33, 0xd4, 0x2f, 0x28, 0xca, 0xcc, 0xcd, 0x2c, 0xc9, 0x2c, 0x4b, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2c, 0x2e, 0x48, 0x2c, 0xca, 0xce, 0x49, 0xd5, 0x83,
	0x28, 0xd1, 0x2b, 0x33, 0x54, 0x32, 0xe1, 0x62, 0x0b, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0x17, 0x12,
	0xe2, 0x62, 0x71, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85,
	0xc4, 0xb8, 0xd8, 0x3c, 0x8b, 0xfd, 0x4a, 0x73, 0x72, 0x24, 0x98, 0x14, 0x18, 0x35, 0x38, 0x82,
	0xa0, 0x3c, 0x90, 0x2e, 0xbf, 0xd2, 0xdc, 0xa4, 0xd4, 0x22, 0x14, 0x5d, 0xcc, 0x04, 0x74, 0xa9,
	0x72, 0x71, 0x86, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x08, 0x49, 0x70, 0xb1, 0x07,
	0xa7, 0x26, 0xe7, 0xe7, 0xa5, 0x14, 0x43, 0xf5, 0xc2, 0xb8, 0x5a, 0xda, 0x5c, 0x6c, 0xee, 0xa9,
	0x79, 0x29, 0xa9, 0x45, 0x42, 0x1c, 0x5c, 0x2c, 0xbe, 0x89, 0x39, 0xa9, 0x02, 0x0c, 0x42, 0x5c,
	0x5c, 0x6c, 0x6e, 0xa9, 0xb9, 0x20, 0x36, 0xa3, 0x10, 0x37, 0x17, 0x7b, 0x68, 0x5e, 0x76, 0x5e,
	0x7e, 0x79, 0x9e, 0x00, 0x93, 0x53, 0x0f, 0x23, 0x97, 0x68, 0x72, 0x7e, 0xae, 0x1e, 0x86, 0xcf,
	0x9c, 0xf8, 0x02, 0x60, 0xbe, 0x0f, 0x00, 0x79, 0x3e, 0x80, 0x31, 0xca, 0x38, 0x3d, 0xb3, 0x24,
	0xa3, 0x34, 0x09, 0xa4, 0x46, 0x3f, 0x3f, 0xb9, 0x24, 0x3f, 0x2d, 0xbf, 0x22, 0x33, 0x5f, 0x1f,
	0xaa, 0x53, 0xbf, 0x20, 0x3b, 0x5d, 0x1f, 0x1e, 0x74, 0xd6, 0x10, 0x56, 0x99, 0xe1, 0x22, 0x26,
	0xe6, 0x60, 0xe7, 0x88, 0x55, 0x4c, 0x82, 0xc1, 0x50, 0x0b, 0x9c, 0x21, 0x16, 0x84, 0x19, 0x9e,
	0x82, 0x8b, 0xc5, 0x40, 0xc4, 0x62, 0xc2, 0x0c, 0x93, 0xd8, 0xc0, 0x01, 0x6d, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x55, 0x40, 0x7c, 0x4c, 0x85, 0x01, 0x00, 0x00,
}
